const bootstrapContext = {
    metaDescription: "sfbmarketplace is a free web-based application. It allows you to use and manage business applications in one simple and secure site, from anywhere.",
    metaKeywords: "sfbmarketplace, saas, applications, marketplace, web-based apps, business apps",
    analyticsId: null,
    marketPlaceName: "sfbmarketplace",
    theme: "acme",
    variation: null,
    locale: "en-US",
    localeLanguage: "en",
    dateFormat: "MM/DD/YY",
    dateTimeFormat: "MM/DD/YY h:mm:ss a",
    defaultCurrency: "USD",
    defaultCountry: null,
    appWiseUrl: "https://appwise.appdirect.com",
    hermesOnInstance: true,
    hermesOnPartner: false,
    hermesSettingsFlag: true,
    hasCustomPaymentGateway: false,
    devMode: false,
    urlProvisioned: true,
    sftpConfigured: false,
    externalReportingEnabled: true,
    gdprSelfServiceEnabled: false,
    companyGroupsEnabled: true,
    paymentConnectorConfigV2Enabled: false,
    accountPaymentsUiV2Enabled: false,
    adminPaymentsUiV2Enabled: false,
    accountPaymentMethodUIV2Enabled: false,
    segmentConditionsOnNotification: true,
    emailAttachmentsEnabled: true,
    capitalCardEnabled: false,
    capitalAdvanceEnabled: false,
    capitalTradeEnabled: false,
    rcSettingsEnabled: false,
    notificationsContinuousProcessingEnabled: true,
    displayV2NotificationsOnly: false,
    customerOnboardingEnabled: false,
    notificationsCustomAttributesSupport: true,
    opportunitiesInQuotesListingEnabled: false,
    networkProductCustomizationFFValue: true,
    currencyFormats: {
        USD: {
            symbol: "$",
            decimal: ".",
            thousand: ",",
            precision: 2,
            format: "%s%v"
        }
    },
    universalHeaderSignalsSocketEndpoint: "wss://signals.us.appdirect.com",
    universalHeaderOAuthClientId: "6wGGP5zZih",
    clientConfiguredCorrectlyForImplicitFlow: true,
    UserInfo: {
        profilePic: null,
        name: "Marketplace",
        email: "marketplace.manager.turcu@appdirect.com",
        verified: true,
        locale: "en_US",
        tester: false,
        currency: "USD",
        hasCustomerContract: false,
        showSetupGuide: true,
        customerContractEditionUuids: [],
        ownedPartners: [],
        user_id: "9dda461e-e7cc-4137-85dd-fbe8b9f7e94e",
        given_name: "Marketplace Manager",
        family_name: "Manager",
        company_id: "1df65377-7269-4368-b671-1d129d966b4e",
        roles: [
            "DISABLE_COMPANY_USER_ACCOUNT",
            "MANAGE_SCHEDULED_REPORTS",
            "CREATE_REPORTS",
            "DELETE_REPORTS",
            "ROLES_MANAGEMENT",
            "CREATE_QUOTE",
            "REPORTS_CHANNEL_ADMIN",
            "CHANNEL_PRODUCT_SUPPORT",
            "SET_OPPORTUNITY_PROVISIONING_DATE",
            "PURCHASE_ON_BEHALF_OF_ALL_USERS",
            "LICENSES_MANAGEMENT_ACCESS",
            "CHANNEL_SUPPORT",
            "SALES_SUPPORT",
            "MANAGE_REPORT_TEMPLATES",
            "CREATE_REPORT_TEMPLATES",
            "MIGRATION_COMPANY_ACCESS",
            "CANCEL_SUBSCRIPTION",
            "DEVELOPER",
            "BILLING_ADMIN",
            "MIGRATION_CHANNEL_ACCESS",
            "USER",
            "QUOTE_SET_RETAIL_PRICE",
            "SET_OPPORTUNITY_BILLING_DATE",
            "DISABLE_COMPANY",
            "JOIN_COMPANY",
            "SYS_ADMIN",
            "CHANNEL_ADMIN",
            "ENABLE_DOMAIN_VERIFICATION"
        ],
        attributes: {
            HAS_CUSTOMER_CONTRACT: "false"
        },
        customUserAttributes: {},
        customUserAttributesIds: {}
    },
    CHANNEL_SETTINGS: {
        partner: "SFBMARKETPLACE",
        linkedPartnerUrl: null,
        companyName: "sfbmarketplace",
        allowSalesAgentEnterPaymentDetails: true,
        accountInvoiceV2Enabled: false,
        invoiceTemplatesEnabled: false,
        resellerInvoiceTemplatesEnabled: false,
        commissionsImporterEnabled: false,
        invoicePdfArchivalEnabled: false,
        invoiceRetentionPeriod: 120,
        meteredUsageEnabled: false,
        meteredUsageV2Enabled: false,
        invoicePaymentTerms: false,
        adminInvoiceV2: false,
        accountPurchaseUIEnabled: false,
        adminPurchaseUIEnabled: false,
        resellerPurchaseUIEnabled: false,
        developerPurchaseUIEnabled: false,
        providerQuotesEnabled: false,
        resellerInvoiceV2Enabled: false,
        resellerInvoiceSettingsEnabled: false,
        accountPaymentMethodUIV2: false,
        invoiceCoreFeed: false,
        creditNotesEnabled: false,
        marketplaceInvoiceSequenceNumber: true,
        fulfillmentActionsEnabled: false,
        shippingCostEnabled: false,
        developerFulfillmentActionsEnabled: false,
        localizationServiceEnabled: true,
        subscriptionCustomAttributesEnabled: true,
        purchaseCustomAttributesEnabled: true,
        assignmentToInactiveUsersEnabled: true,
        allowDiscountCredit: true,
        configuratorAddToCartCTAEnabled: false,
        useCheckoutV2ForAllProducts: false,
        showTermsConditionsInCheckoutV2: false,
        approvesUserContent: false,
        currency: "USD",
        currencies: [
            "USD"
        ],
        hideAllUI: false,
        hideQuestions: false,
        hideSupportSection: false,
        supportRequired: false,
        featuresRequired: true,
        identityProvider: false,
        includeCaptchaInRegistration: false,
        localeTags: [
            "en-US"
        ],
        defaultLocale: "en-US",
        defaultLocaleCountry: "US",
        defaultLocaleCountryIso3: "USA",
        minimumReviewsForRating: 1,
        oneClickTrialEnabled: false,
        channelDecidesIfOnlyAdminsCanBuy: false,
        collectPurchaseRequestDetails: false,
        partnerName: "sfbmarketplace",
        recaptchaPublicKey: null,
        reviewRequirePurchase: false,
        displayTaxBreakdown: false,
        displayTaxSubtotal: false,
        flatTaxRate: null,
        supportContactUrl: null,
        supportUrl: null,
        supportPhone: null,
        supportEmail: null,
        privacyPolicyUrl: null,
        legalDetailsUrl: null,
        termsUrl: null,
        trustedProviders: [],
        agreeToTermsForOneClickBuy: false,
        importAppsEnabled: false,
        cmsCurrencies: [
            "USD"
        ],
        hideSignupLinks: false,
        appUserSyncBaseUrl: null,
        capabilities: [
            "CHANNEL_PAYMENT_GATEWAY",
            "PRODUCT_PURCHASE",
            "CHANNEL_MANAGEMENT",
            "CUSTOMER_BILLING_MANAGEMENT",
            "NETWORK_CATALOG",
            "FULL_PRODUCT_INTEGRATION",
            "CHECKOUT",
            "STORE_FRONT",
            "SECURITY_SETTINGS",
            "HOSTED_CHECKOUT",
            "PRODUCT_BUNDLES",
            "QUESTIONS_AND_ANSWERS",
            "DEVELOPER",
            "DEVELOPER_NETWORK",
            "CUSTOMER_APPLICATION_MANAGEMENT",
            "USER_MANAGEMENT"
        ],
        boostEnabled: false,
        hideCustomerInfoFromDevelopers: false,
        developerDocsUrl: null,
        manualPaymentsOnly: false,
        hideBillingInfoShortcut: false,
        showInvoicePage: true,
        showPaymentPage: true,
        manualPaymentsEnabled: false,
        selfManagedCompanyStructure: false,
        externallyManagedRoles: false,
        guideProgresses: {
            CHANNEL: 1000,
            BILLING: 3
        },
        integrationProvider: false,
        manualEventRecoveryEnabled: false,
        salesOpportunitiesEnabled: false,
        sendActivationEmailFromOpportunitiesEnabled: false,
        canFinalizeOpportunityWithInactiveUserEnabled: true,
        cannotSubmitOpportunityWithErrorsEnabled: false,
        salesLeadsEnabled: false,
        developerLeadsFlowEnabled: false,
        apiAndIntegrationEventsEnabled: false,
        developerCanSelectApplicationCountries: false,
        allowCheckoutV1FlowOnAssistedSale: true,
        developerCanSelectApplicationCurrencies: false,
        betaLeadsV2Enabled: false,
        betaLeadToOrderMultiProductEnabled: false,
        betaResellerDashboardEnabled: false,
        betaResellerDashboardChartsEnabled: false,
        resellerDashboardCreditMetricsEnabled: false,
        managePaymentsOfBehalfOfEnabled: false,
        domainsResellerEditionId: null,
        showProfiles: true,
        hideChannelUserInfoFromCustomers: false,
        resellerTermsUrl: null,
        resellerLeadsTermsUrl: null,
        showSocialMediaLinks: false,
        hidePricingsFromUnauthenticatedUserEnabled: false,
        showV2HomePageTheme: true,
        myAppsAfterLogin: true,
        showV2ListingPageTheme: true,
        showBillingCycleDay: false,
        showV2ProfilePageTheme: true,
        showV2CheckoutPageTheme: true,
        marketplaceEdition: "STORE",
        marketplaceName: "sfbmarketplace",
        customLogo: "https://d3bql97l1ytoxn.cloudfront.net/marketplace_logo/defaultlogo.png?988e84efc1a891b025e6d5c7eff56d27",
        customFavicon: null,
        taxIncludedInPrices: false,
        taxExemptionCodeNotRestricted: false,
        useExternalIdForApi: false,
        buyingDeskEnabled: false,
        purchaseRemoteApprovalV2Enabled: false,
        accountStatus: "PAID",
        trialExpirationDate: null,
        baseSupportUrl: null,
        accountEdition: null,
        marketplaceAccount: null,
        autoUpgradeToPaid: false,
        autoPay: true,
        usePaymentService: true,
        flowThroughPaymentService: false,
        usePaymentsFramework: false,
        paymentsHandledFullyOffPlatform: false,
        editionLevelOverride: false,
        termsForAllProductPurchasesRequired: false,
        termsForAllProductPurchasesUrl: null,
        usersCanCompleteOwnQuotes: true,
        oneClickMigrationEnabled: false,
        oneClickProvisioningEnabled: false,
        twoFactorEnabled: false,
        twoFactorTrustedDeviceEnabled: false,
        twoFactorTrustedDeviceForDaysCount: 14,
        smsGatewayType: "NONE",
        supportedProductTypes: [
            "WEB_APP"
        ],
        changeOwnershipRequestEmail: null,
        domainReactivationEmail: null,
        reportsEmail: null,
        marketplaceCreditEnabled: false,
        smsNotificationsEnabled: false,
        walkMeEnabled: true,
        hasSampleContent: false,
        betaWholesaleQuotesEnabled: true,
        alwaysUseManualPaymentForCustomerOrders: false,
        allowChannelAdminToVoidInvoice: false,
        versionManagementApiClientId: null,
        passwordPolicy: "password.policy",
        passwordPolicyRegex: "(?=.{8,})((?=.*\d)|(?=.*\W))((?=.*[A-Z])|(?=.*[a-z])).*",
        selfServiceRestrictionEnabled: false,
        devicePlatformsEnabled: false,
        productVersionsEnabled: false,
        webAccessibleProductVersionsEnabled: false,
        deviceGroupsEnabled: false,
        betaShippingSettingsEnabled: false,
        channelPlatformManagementEnabled: true,
        channelDeviceManagementEnabled: true,
        deviceBrowsingEnabled: false,
        pushDistributionsEnabled: false,
        productVersionsBaseUrl: null,
        odsaBaseUrl: null,
        odsaRoleRestricted: true,
        betaAppleDepEnabled: false,
        webhookProxyInfo: {
            webhookProxyEnabled: false,
            webhookProxyUrl: null,
            webhookProxySecurityKey: null,
            webhookProxySecuritySecret: null
        },
        docCenterBaseLandingUrl: "https://ad.docs.appdirect.com/redirect/login?openid=",
        channelCanonicalBaseUrl: "https://sfbmarketplace.byappdirect.com",
        showV2AppAssignments: true,
        showV2GroupAppAssignments: true,
        showV2RolesManagement: false,
        betaResellerProfileV2Enabled: false,
        reportingEnabled: false,
        demoFeatures: false,
        companyWideBilling: false,
        docCenterProvisioned: true,
        notificationsEnabled: true,
        advancedNotificationSystemState: "DISABLED",
        resellerProfilesEnabled: false,
        genericUserSyncEnabled: false,
        dataConnectorsEnabled: false,
        fullAzureSyncEnabled: false,
        migrationVendorValidationEnabled: true,
        preAuthorizePayment: true,
        universalHeaderEnabled: false,
        universalHeaderForBusinessUnitsEnabled: false,
        fetchAccessTokenOnLoginEnabled: true,
        bundleProductsFromMultipleVendors: true,
        canExitCheckoutFlow: true,
        checkoutV2Enabled: true,
        useCompanyNameInBOBO: false,
        showFAQInBOBO: true,
        canDownloadOrderPDFInBOBO: true,
        countryDropdownConfigurable: false,
        supportedCountries: [],
        vatMandatoryCountries: [],
        defaultCountry: null,
        paymentSettingsV2: true,
        betaReferralCompaniesEnabled: false,
        baseChannel: false,
        developerReportCenterEnabled: false,
        companyAdminReportCenterEnabled: false,
        corporateAdminReportCenterEnabled: false,
        resellerReportCenterEnabled: false,
        resellerManagerReportCenterEnabled: false,
        reportCenterTemplatesEnabled: true,
        enhancedEcommerceAnalyticsEnabled: false,
        customizeThemeLinkEnabled: true,
        storefrontBuilderEnabled: true,
        storefrontBuilderPublishedThemeEnabled: true,
        storefrontBuilderLayoutEditorEnabled: true,
        allowNativeLogin: false,
        googleInboundConnectorEnabled: false,
        autoAddProductToResellerCatalog: false,
        allowNonUniqueEmailAddress: false,
        betaCompanyListV2Enabled: false,
        betaUserListV2Enabled: false,
        betaCompanyV2Enabled: false,
        managedUsersEnabled: false,
        betaUserV2Enabled: false,
        showCompanyExternalIdOnList: false,
        heapAnalyticsEnabled: false,
        phoneNumberRequired: false,
        allowExternalReferenceCode: false,
        betaPurchaseSetupEnabled: false,
        betaOpportunitiesEnabled: false,
        betaOnboardCspEnabled: false,
        addonStoreIntegrationEnabled: true,
        addonStoreUrl: "https://addons.appdirect.com",
        purchaseRemoteApprovalEnabled: false,
        delayInvoicingForCombinedPurchase: false,
        defaultSalePriceToMarketplaceSalePrice: false,
        showProductMarketplaceSalePrice: false,
        showWholesalePriceForMarketplace: true,
        allowDailyPurchaseLimitCompanyOverride: false,
        allowThirtyDaysPurchaseLimitCompanyOverride: false,
        reconciliationFundTransfersEnabled: false,
        bulkResellerReconciliationTransfersEnabled: false,
        paymentMethodPermissionsEnabled: false,
        taxIdentificationNumberValidationEnabled: false,
        disableCSRCSVDownload: false,
        disableSSRCSVDownload: false,
        companyBookmarkEnabled: false,
        checkoutV2UIEnabled: true,
        publishMicrosoftOrderEventsAsyncEnabled: false,
        syndicationToCspTransitionMenuLinkVisible: false,
        syncSettingsMenuLinkVisible: false,
        collectBillingAddressForOffPlatformPaymentMethodEnabled: false,
        hideSystemManagedGroups: false,
        gracefulBlockingEnabled: false,
        adpCustomizedErrorPageUrl: null,
        allowCreateCompaniesByUI: true,
        cartLockingEnabled: false,
        ownerBaseUrlMap: null,
        betaAccountActivationV2Enabled: false,
        licenseManagementEnabled: false,
        betaUserMembershipActivationV2Enabled: false,
        betaUserLoginV2Enabled: false,
        resellersTransferMethodPlatformType: "PAYPAL",
        billingRelationshipsConfigurationEnabled: false,
        spreedlyConfigured: false,
        selfserveMarketplace: false,
        buyAlwaysRequiresBillingInfo: false,
        buyFreeTrialRequiresBillingInfo: false,
        buyFullyDiscountedRequiresBillingInfo: false,
        onlyAdminsCanBuy: false,
        alwaysUseManualPaymentForSalesAgentOrders: false,
        companyNotesEnabled: false,
        offOrderChargeEnabled: false,
        manageCompanyOnBehalfOf: true,
        resellerCatalogSecondaryNavItem: false,
        resellerAppSmartPortalChanges: false,
        enableDomainVerification: true,
        paymentFirstEnabled: false,
        usageReadersEnabled: false,
        externalUrlMap: {},
        canEnableSSRMigrationCompanyAccess: false,
        hideOriginalPriceToCustomer: false,
        networkProductCustomizationEnabled: true,
        test: false,
        exportReconciliationLinesEnabled: false,
        baas: false,
        cmsEnabled: true,
        emailBasedIdp: false,
        ldapSyncEnabled: false,
        quoteConfiguredForResellers: false,
        listingOnly: false,
        salesAgentPurchaseApproved: false,
        integrationConfigurationReadOnly: false,
        inviteMarketplace: false
    },
    CompanyInfo: {
        uuid: "1df65377-7269-4368-b671-1d129d966b4e",
        name: "sfbmarketplace",
        partner: "SFBMARKETPLACE",
        contactInformation: {
            phone: "5142417385"
        },
        salesOpportunitiesEnabled: false,
        salesLeadsEnabled: false,
        resellersCanCreateCompanies: true,
        resellersCanManageCustomers: true,
        needsBoostMosiTerms: false,
        externalIdentifier: null,
        passwordPolicy: "password.policy",
        passwordPolicyRegex: "(?=.{8,})((?=.*\d)|(?=.*\W))((?=.*[A-Z])|(?=.*[a-z])).*",
        onlyAdminsCanBuy: false,
        importAppsEnabled: false,
        companyWideBilling: false,
        channelAdmin: true,
        vendor: true,
        reseller: false
    },
    CurrentUser: {
        id: 11435715,
        uuid: "9dda461e-e7cc-4137-85dd-fbe8b9f7e94e",
        uuidHash: "+XbcVmudOuUe68r46d/5pySyv9mss/PgCVhYmXn5S0E=",
        externalId: null,
        email: "marketplace.manager.turcu@appdirect.com",
        customerProfile: false,
        impersonated: false,
        restrictedSalesSupport: false,
        tester: false,
        developer: true,
        channelSupport: true,
        superuser: false,
        channelProductSupport: true,
        sysAdmin: true,
        billingAdmin: true,
        channelAdmin: true,
        salesSupport: true,
        referral: false,
        reportsChannelAdmin: true,
        isChannelAdmin: true,
        isReportsChannelAdmin: true,
        isChannelProductSupport: true,
        isChannelSupport: true,
        isBillingAdmin: true,
        isSalesSupport: true,
        isDeveloper: true,
        isTester: false,
        isRestrictedSalesSupport: false,
        isReferral: false,
        isSysAdmin: true,
        isImpersonated: false,
        isSuperuser: false
    },
    WEBSHIM_PATH: "https://d6r6ulbtqyuv7.cloudfront.net/wicket/resource/com.appdirect.wicket.resources.Resource/common/js/vendor/webshim/js-webshim/minified/shims/",
    ACE_PATH: "https://d6r6ulbtqyuv7.cloudfront.net/wicket/resource/com.appdirect.wicket.resources.Resource/common/js/vendor/ace/src-min/",
    IMG_BASE: "https://d3bql97l1ytoxn.cloudfront.net",
    CONTEXT_PATH: "",
    SERVER_TIME_ZONE: "-04:00",
    DATE_PICKER_FORMAT: "mm/dd/yy"
}

module.exports = bootstrapContext;