const bootstrapContext = {
  metaDescription: "AppSmart allows you to use and manage business applications in one simple and secure platform, from anywhere.",
  metaKeywords: "AppSmart, saas, applications, marketplace, web-based apps, business apps",
  analyticsId: "UA-121599838-2",
  marketPlaceName: "AppSmart Marketplace",
  theme: "appsmart",
  variation: null,
  locale: "en-US",
  localeLanguage: "en",
  dateFormat: "MM/DD/YY",
  dateTimeFormat: "MM/DD/YY h:mm:ss a",
  defaultCurrency: "USD",
  defaultCountry: "US",
  appWiseUrl: "https://appwise.appdirect.com",
  hermesOnInstance: true,
  hermesOnPartner: true,
  hermesSettingsFlag: true,
  hasCustomPaymentGateway: false,
  devMode: false,
  urlProvisioned: true,
  sftpConfigured: false,
  externalReportingEnabled: true,
  gdprSelfServiceEnabled: false,
  companyGroupsEnabled: true,
  paymentConnectorConfigV2Enabled: false,
  accountPaymentsUiV2Enabled: false,
  adminPaymentsUiV2Enabled: false,
  accountPaymentMethodUIV2Enabled: false,
  segmentConditionsOnNotification: true,
  emailAttachmentsEnabled: true,
  capitalCardEnabled: false,
  capitalAdvanceEnabled: false,
  capitalTradeEnabled: false,
  rcSettingsEnabled: false,
  notificationsContinuousProcessingEnabled: true,
  displayV2NotificationsOnly: false,
  customerOnboardingEnabled: false,
  notificationsCustomAttributesSupport: true,
  opportunitiesInQuotesListingEnabled: false,
  networkProductCustomizationFFValue: true,
  currencyFormats: {
    USD: {
      symbol: "$",
      decimal: ".",
      thousand: ",",
      precision: 2,
      format: "%s%v"
    }
  },
  universalHeaderSignalsSocketEndpoint: "wss://signals.us.appdirect.com",
  universalHeaderOAuthClientId: "6wGGP5zZih",
  clientConfiguredCorrectlyForImplicitFlow: true,
  UserInfo: {
  profilePic: null,
  name: "{Username} LastName",
  email: "Username.lastname@email.com",
  verified: true,
  locale: "en_US",
  tester: false,
  currency: "USD",
  hasCustomerContract: false,
  showSetupGuide: true,
  customerContractEditionUuids: [],
  ownedPartners: [],
  user_id: "1290b26b-ab80-4971-a4a2-1d9f333416cc",
  given_name: "{Username}",
  family_name: "LastName",
  company_id: "1b0c65dc-d4a0-4e12-a2a0-042412500721",
  roles: [
    "USER"
  ],
  attributes: {
    HAS_CUSTOMER_CONTRACT: "false"
  },
  customUserAttributes: {},
  customUserAttributesIds: {}
},
  CHANNEL_SETTINGS: {
    partner: "APPSMART",
    linkedPartnerUrl: null,
    companyName: "AppSmart",
    allowSalesAgentEnterPaymentDetails: true,
    accountInvoiceV2Enabled: true,
    invoiceTemplatesEnabled: true,
    resellerInvoiceTemplatesEnabled: false,
    commissionsImporterEnabled: true,
    invoicePdfArchivalEnabled: true,
    invoiceRetentionPeriod: 120,
    meteredUsageEnabled: false,
    meteredUsageV2Enabled: false,
    invoicePaymentTerms: true,
    adminInvoiceV2: true,
    accountPurchaseUIEnabled: true,
    adminPurchaseUIEnabled: true,
    resellerPurchaseUIEnabled: false,
    developerPurchaseUIEnabled: false,
    providerQuotesEnabled: true,
    resellerInvoiceV2Enabled: false,
    resellerInvoiceSettingsEnabled: false,
    accountPaymentMethodUIV2: false,
    invoiceCoreFeed: true,
    creditNotesEnabled: false,
    marketplaceInvoiceSequenceNumber: false,
    fulfillmentActionsEnabled: true,
    shippingCostEnabled: false,
    developerFulfillmentActionsEnabled: false,
    localizationServiceEnabled: true,
    subscriptionCustomAttributesEnabled: true,
    purchaseCustomAttributesEnabled: true,
    assignmentToInactiveUsersEnabled: true,
    allowDiscountCredit: true,
    configuratorAddToCartCTAEnabled: false,
    useCheckoutV2ForAllProducts: true,
    showTermsConditionsInCheckoutV2: false,
    approvesUserContent: true,
    currency: "USD",
    currencies: [
      "USD"
    ],
    hideAllUI: false,
    hideQuestions: true,
    hideSupportSection: false,
    supportRequired: false,
    featuresRequired: true,
    identityProvider: false,
    includeCaptchaInRegistration: false,
    localeTags: [
      "en-US"
    ],
    defaultLocale: "en-US",
    defaultLocaleCountry: "US",
    defaultLocaleCountryIso3: "USA",
    minimumReviewsForRating: 1,
    oneClickTrialEnabled: false,
    channelDecidesIfOnlyAdminsCanBuy: false,
    collectPurchaseRequestDetails: true,
    partnerName: "AppSmart",
    recaptchaPublicKey: null,
    reviewRequirePurchase: true,
    displayTaxBreakdown: false,
    displayTaxSubtotal: false,
    flatTaxRate: null,
    supportContactUrl: "https://support.appsmart.com/",
    supportUrl: "https://support.appsmart.com/",
    supportPhone: "866-456-3211",
    supportEmail: "help@appsmart.com",
    privacyPolicyUrl: "https://www.appsmart.com/legal",
    legalDetailsUrl: null,
    termsUrl: "https://www.appsmart.com/legal",
    trustedProviders: [],
    agreeToTermsForOneClickBuy: false,
    importAppsEnabled: true,
    cmsCurrencies: [
      "USD"
    ],
    hideSignupLinks: true,
    appUserSyncBaseUrl: "https://prod-app-sync.cfapps.io",
    capabilities: [
      "DEVELOPER",
      "USER_MANAGEMENT",
      "CUSTOMER_APPLICATION_MANAGEMENT",
      "RESELLER",
      "CHANNEL_PAYMENT_GATEWAY",
      "RESELLER_SIGNUP",
      "CHANNEL_MANAGEMENT",
      "PRODUCT_PURCHASE",
      "QUESTIONS_AND_ANSWERS",
      "CHECKOUT",
      "CUSTOMER_BILLING_MANAGEMENT",
      "NETWORK_CATALOG",
      "STORE_FRONT",
      "SECURITY_SETTINGS",
      "FULL_PRODUCT_INTEGRATION",
      "MIGRATION",
      "PRODUCT_BUNDLES",
      "HOSTED_CHECKOUT",
      "DEVELOPER_NETWORK"
    ],
    boostEnabled: false,
    hideCustomerInfoFromDevelopers: false,
    developerDocsUrl: "https://docs.appdirect.com/developer/distribution",
    manualPaymentsOnly: false,
    hideBillingInfoShortcut: false,
    showInvoicePage: true,
    showPaymentPage: true,
    manualPaymentsEnabled: true,
    selfManagedCompanyStructure: false,
    externallyManagedRoles: false,
    guideProgresses: {
      CHANNEL: 1000,
      BILLING: 1000
    },
    integrationProvider: false,
    manualEventRecoveryEnabled: true,
    salesOpportunitiesEnabled: true,
    sendActivationEmailFromOpportunitiesEnabled: true,
    canFinalizeOpportunityWithInactiveUserEnabled: false,
    cannotSubmitOpportunityWithErrorsEnabled: true,
    salesLeadsEnabled: true,
    developerLeadsFlowEnabled: false,
    apiAndIntegrationEventsEnabled: false,
    developerCanSelectApplicationCountries: false,
    allowCheckoutV1FlowOnAssistedSale: true,
    developerCanSelectApplicationCurrencies: false,
    betaLeadsV2Enabled: true,
    betaLeadToOrderMultiProductEnabled: false,
    betaResellerDashboardEnabled: true,
    betaResellerDashboardChartsEnabled: true,
    resellerDashboardCreditMetricsEnabled: false,
    managePaymentsOfBehalfOfEnabled: true,
    domainsResellerEditionId: 480780,
    showProfiles: true,
    hideChannelUserInfoFromCustomers: true,
    resellerTermsUrl: "",
    resellerLeadsTermsUrl: "",
    showSocialMediaLinks: true,
    hidePricingsFromUnauthenticatedUserEnabled: false,
    showV2HomePageTheme: true,
    myAppsAfterLogin: true,
    showV2ListingPageTheme: true,
    showBillingCycleDay: false,
    showV2ProfilePageTheme: true,
    showV2CheckoutPageTheme: false,
    marketplaceEdition: "STORE",
    marketplaceName: "AppSmart Marketplace",
    customLogo: "https://d3bql97l1ytoxn.cloudfront.net/marketplace_logo/img7112784765708265925.jpg?f7ac0610eb204b73007248f09f36a0e9",
    customFavicon: "https://d3bql97l1ytoxn.cloudfront.net/marketplace_favicon/img7689238228774973938.jpg?69392dd2bff884a0931f8be7adda50bb",
    taxIncludedInPrices: false,
    taxExemptionCodeNotRestricted: false,
    useExternalIdForApi: false,
    buyingDeskEnabled: false,
    purchaseRemoteApprovalV2Enabled: false,
    accountStatus: "PAID",
    trialExpirationDate: null,
    baseSupportUrl: null,
    accountEdition: null,
    marketplaceAccount: null,
    autoUpgradeToPaid: true,
    autoPay: true,
    usePaymentService: true,
    flowThroughPaymentService: false,
    usePaymentsFramework: false,
    editionLevelOverride: true,
    termsForAllProductPurchasesRequired: false,
    termsForAllProductPurchasesUrl: null,
    usersCanCompleteOwnQuotes: true,
    oneClickMigrationEnabled: false,
    oneClickProvisioningEnabled: false,
    twoFactorEnabled: true,
    twoFactorTrustedDeviceEnabled: true,
    twoFactorTrustedDeviceForDaysCount: 14,
    smsGatewayType: "TWILIO",
    supportedProductTypes: [
      "STATIC",
      "WEB_APP",
      "EXTERNAL",
      "EMBEDDED_VIDEO",
      "WEB_APP_MANUAL_SETUP",
      "DOMAIN_RESELLER",
      "HARDWARE_SERVICE",
      "WEB_APP_STACKED",
      "CLOUD_SERVICES",
      "PHYSICAL_PRODUCT",
      "DOWNLOAD_WITH_FULL_PROFILE"
    ],
    changeOwnershipRequestEmail: null,
    domainReactivationEmail: null,
    reportsEmail: null,
    marketplaceCreditEnabled: false,
    smsNotificationsEnabled: false,
    walkMeEnabled: true,
    hasSampleContent: false,
    betaWholesaleQuotesEnabled: true,
    alwaysUseManualPaymentForCustomerOrders: false,
    allowChannelAdminToVoidInvoice: true,
    versionManagementApiClientId: null,
    passwordPolicy: "password.policy",
    passwordPolicyRegex: "(?=.{8,})((?=.*\d)|(?=.*\W))((?=.*[A-Z])|(?=.*[a-z])).*",
    selfServiceRestrictionEnabled: false,
    devicePlatformsEnabled: false,
    productVersionsEnabled: false,
    webAccessibleProductVersionsEnabled: false,
    deviceGroupsEnabled: false,
    betaShippingSettingsEnabled: true,
    channelPlatformManagementEnabled: true,
    channelDeviceManagementEnabled: true,
    deviceBrowsingEnabled: false,
    pushDistributionsEnabled: false,
    productVersionsBaseUrl: null,
    odsaBaseUrl: null,
    odsaRoleRestricted: true,
    betaAppleDepEnabled: false,
    webhookProxyInfo: {
      webhookProxyEnabled: false,
      webhookProxyUrl: null,
      webhookProxySecurityKey: null,
      webhookProxySecuritySecret: null
    },
    docCenterBaseLandingUrl: "https://ad.docs.appdirect.com/redirect/login?openid=",
    channelCanonicalBaseUrl: "https://marketplace.appsmart.com",
    showV2AppAssignments: true,
    showV2GroupAppAssignments: true,
    showV2RolesManagement: true,
    betaResellerProfileV2Enabled: true,
    reportingEnabled: false,
    demoFeatures: false,
    companyWideBilling: true,
    docCenterProvisioned: true,
    notificationsEnabled: true,
    advancedNotificationSystemState: "V1_V2_MERGED",
    resellerProfilesEnabled: true,
    genericUserSyncEnabled: true,
    dataConnectorsEnabled: true,
    fullAzureSyncEnabled: false,
    migrationVendorValidationEnabled: true,
    preAuthorizePayment: false,
    universalHeaderEnabled: true,
    universalHeaderForBusinessUnitsEnabled: true,
    fetchAccessTokenOnLoginEnabled: false,
    bundleProductsFromMultipleVendors: true,
    canExitCheckoutFlow: true,
    checkoutV2Enabled: true,
    useCompanyNameInBOBO: false,
    showFAQInBOBO: true,
    canDownloadOrderPDFInBOBO: true,
    countryDropdownConfigurable: false,
    supportedCountries: [],
    vatMandatoryCountries: [],
    defaultCountry: null,
    paymentSettingsV2: false,
    betaReferralCompaniesEnabled: true,
    baseChannel: false,
    developerReportCenterEnabled: false,
    companyAdminReportCenterEnabled: true,
    corporateAdminReportCenterEnabled: false,
    resellerReportCenterEnabled: true,
    resellerManagerReportCenterEnabled: true,
    reportCenterTemplatesEnabled: true,
    enhancedEcommerceAnalyticsEnabled: false,
    customizeThemeLinkEnabled: true,
    storefrontBuilderEnabled: true,
    storefrontBuilderPublishedThemeEnabled: true,
    storefrontBuilderLayoutEditorEnabled: false,
    allowNativeLogin: false,
    googleInboundConnectorEnabled: true,
    autoAddProductToResellerCatalog: false,
    allowNonUniqueEmailAddress: false,
    betaCompanyListV2Enabled: true,
    betaUserListV2Enabled: true,
    betaCompanyV2Enabled: true,
    managedUsersEnabled: true,
    betaUserV2Enabled: true,
    showCompanyExternalIdOnList: false,
    heapAnalyticsEnabled: false,
    phoneNumberRequired: false,
    allowExternalReferenceCode: false,
    betaPurchaseSetupEnabled: true,
    betaOpportunitiesEnabled: true,
    betaOnboardCspEnabled: true,
    addonStoreIntegrationEnabled: true,
    addonStoreUrl: "https://addons.appdirect.com",
    purchaseRemoteApprovalEnabled: false,
    delayInvoicingForCombinedPurchase: false,
    defaultSalePriceToMarketplaceSalePrice: false,
    showProductMarketplaceSalePrice: false,
    showWholesalePriceForMarketplace: false,
    allowDailyPurchaseLimitCompanyOverride: false,
    allowThirtyDaysPurchaseLimitCompanyOverride: false,
    reconciliationFundTransfersEnabled: true,
    bulkResellerReconciliationTransfersEnabled: true,
    paymentMethodPermissionsEnabled: true,
    taxIdentificationNumberValidationEnabled: false,
    disableCSRCSVDownload: false,
    disableSSRCSVDownload: false,
    companyBookmarkEnabled: false,
    checkoutV2UIEnabled: true,
    publishMicrosoftOrderEventsAsyncEnabled: false,
    syndicationToCspTransitionMenuLinkVisible: false,
    syncSettingsMenuLinkVisible: true,
    collectBillingAddressForOffPlatformPaymentMethodEnabled: false,
    hideSystemManagedGroups: false,
    gracefulBlockingEnabled: false,
    adpCustomizedErrorPageUrl: null,
    allowCreateCompaniesByUI: true,
    cartLockingEnabled: false,
    ownerBaseUrlMap: {
      APPDIRECT2: "https://store.appdirect.com"
    },
    betaAccountActivationV2Enabled: true,
    licenseManagementEnabled: false,
    betaUserMembershipActivationV2Enabled: true,
    betaUserLoginV2Enabled: true,
    resellersTransferMethodPlatformType: "STRIPE",
    billingRelationshipsConfigurationEnabled: true,
    spreedlyConfigured: false,
    selfserveMarketplace: false,
    buyAlwaysRequiresBillingInfo: false,
    buyFreeTrialRequiresBillingInfo: true,
    buyFullyDiscountedRequiresBillingInfo: false,
    onlyAdminsCanBuy: true,
    alwaysUseManualPaymentForSalesAgentOrders: false,
    companyNotesEnabled: true,
    offOrderChargeEnabled: true,
    manageCompanyOnBehalfOf: true,
    resellerCatalogSecondaryNavItem: true,
    resellerAppSmartPortalChanges: true,
    enableDomainVerification: true,
    paymentFirstEnabled: false,
    usageReadersEnabled: false,
    externalUrlMap: {},
    canEnableSSRMigrationCompanyAccess: false,
    hideOriginalPriceToCustomer: false,
    networkProductCustomizationEnabled: true,
    exportReconciliationLinesEnabled: true,
    ldapSyncEnabled: false,
    listingOnly: false,
    test: false,
    cmsEnabled: true,
    baas: false,
    emailBasedIdp: false,
    inviteMarketplace: true,
    integrationConfigurationReadOnly: false,
    quoteConfiguredForResellers: true,
    salesAgentPurchaseApproved: false
  },
  CompanyInfo: {
    uuid: "3dc98547-47dd-47bb-9b01-4569be3412e6",
    name: "AppSmart",
    partner: "APPSMART",
    contactInformation: {
      street1: "3128 Highwoods Blvd",
      street2: "Ste. 140",
      city: "Raleigh",
      state: "NC",
      zip: "27604",
      country: "US",
      phone: "866-456-3211"
    },
    salesOpportunitiesEnabled: false,
    salesLeadsEnabled: false,
    resellersCanCreateCompanies: true,
    resellersCanManageCustomers: true,
    needsBoostMosiTerms: false,
    externalIdentifier: "2bc11cc0-f07f-e8b0-3b1f-5728e1e81fba",
    passwordPolicy: "password.policy",
    passwordPolicyRegex: "(?=.{8,})((?=.*\d)|(?=.*\W))((?=.*[A-Z])|(?=.*[a-z])).*",
    onlyAdminsCanBuy: false,
    importAppsEnabled: true,
    companyWideBilling: false,
    channelAdmin: true,
    vendor: true,
    reseller: false
  },
  CurrentUser: {
    id: 10597822,
    uuid: "686e180a-8ed5-4164-a776-88c04c9d73fc",
    uuidHash: "7bvAgnwXbJc6JeMi2ksdsWrXpQRM+My9jrKbtYEQJX8=",
    externalId: "Username.lastname@email.com",
    email: "Username.lastname@email.com",
    customerProfile: false,
    impersonated: false,
    restrictedSalesSupport: false,
    tester: false,
    sysAdmin: false,
    billingAdmin: false,
    channelAdmin: false,
    salesSupport: false,
    developer: false,
    channelSupport: false,
    superuser: false,
    channelProductSupport: false,
    referral: false,
    reportsChannelAdmin: false,
    isChannelAdmin: false,
    isReportsChannelAdmin: false,
    isChannelProductSupport: false,
    isChannelSupport: false,
    isBillingAdmin: false,
    isSalesSupport: false,
    isDeveloper: false,
    isTester: false,
    isRestrictedSalesSupport: false,
    isReferral: false,
    isSysAdmin: false,
    isImpersonated: false,
    isSuperuser: false
  },
  WEBSHIM_PATH: "https://d6r6ulbtqyuv7.cloudfront.net/wicket/resource/com.appdirect.wicket.resources.Resource/common/js/vendor/webshim/js-webshim/minified/shims/",
  ACE_PATH: "https://d6r6ulbtqyuv7.cloudfront.net/wicket/resource/com.appdirect.wicket.resources.Resource/common/js/vendor/ace/src-min/",
  IMG_BASE: "https://d3bql97l1ytoxn.cloudfront.net",
  CONTEXT_PATH: "",
  SERVER_TIME_ZONE: "-04:00",
  DATE_PICKER_FORMAT: "mm/dd/yy"
}

module.exports = bootstrapContext
